sudo: required

language: python
python:
    - 3.6
    - 3.6

matrix:
  include:
      - python: 3.6
        env: TOXENV=black
      - python: 3.6
        env: TOXENV=pylama

install:
    - pip install tox tox-travis coveralls

script:
    - tox